frontend server1 -> metric pub/sub
frontend server2 -> metric pub/sub
database server -> metric pub/sub
database replica -> metric pub/sub
chatting server -> metric pub/sub
shopping basket -> metric pub/sub
backend server -> metric pub/sub

metric pub/sub -> metric UI
metric pub/sub -> metric analysis
metric pub/sub -> activity monitoring
metric pub/sub -> database monitoring