1 당신의 인생이다 -> 4 돌멩이 수프와 삶은 개구리
1 당신의 인생이다 -> 6 지식 포트폴리오
2 고양이가 내 소스 코드를 삼켰어요 -> 49 실묭주의 팀
3 소프트웨어 엔트로피 -> 10 직교성
3 소프트웨어 엔트로피 -> 40 리팩터링
3 소프트웨어 엔트로피 -> 44 이름 짓기
4 돌멩이 수프와 삶은 개구리 -> 1 당신의 인생이다
4 돌멩이 수프와 삶은 개구리 -> 38 우연에 맡기는 프로그래밍
5 적당히 괜찮은 소프트웨어 -> 45 요구 사항의 구렁텅이
5 적당히 괜찮은 소프트웨어 -> 46 불가능한 퍼즐 풀기
6 지식 포트폴리오 -> 1 당신의 인생이다
6 지식 포트폴리오 -> 22 엔지니어링 일지
7 소통하라! -> 15 추정
7 소통하라! -> 18 파워 에디팅
7 소통하라! -> 45 요구 사항의 구렁텅이
7 소통하라! -> 49 실용주의 팀